### ISSUE TITLE
Incompatibilidade com Lazy Loading

### ISSUE THREAD

**Issue by gabrielhssilva** [wizsolucoes/wiz-pagination#6]
Ao tentar implementar junto com o Lazy Loaging, ocorre conflito na importação do módulo. Aparentemente está ocorrendo porque está sendo utilizado o BrowserModule na lib.

**Comment by hugosrr17** [comment]
@gabrielhssilva  Fixed!

**Comment by hugosrr17** [comment]
> Ao tentar implementar junto com o Lazy Loaging, ocorre conflito na importação do módulo. Aparentemente está ocorrendo porque está sendo utilizado o BrowserModule na lib.

@gabrielhssilva Fixed!
